### ISSUE TITLE
Instant death register incompatible with Accursed Sceptre

### ISSUE THREAD

**Issue by jrv123** [EIKOOT/nyloer#2]
The Accursed Sceptre behaves differently from other charged tridents such as a Sanguinesti Staff or Trident of the Swamp. The plugin will typically cause a nylocas to instantly become hidden upon a satisfactory xp drop that registers a kill. However, even with a satisfactory xp drop to kill, the plugin remains incompatible with the Accursed Sceptre and the nylos will remain completely visible. Please fix!

**Comment by EIKOOT** [comment]
Nyloer doesn't do NPC hiding last time I checked.

**Comment by EIKOOT** [comment]
issue is related to another plugin.
