### ISSUE TITLE
Feature request: Add option to save sidepanel role swaps

### ISSUE THREAD

**Issue by YvesW** [EIKOOT/nyloer#4]
I have not checked the code yet, but when restarting the client, the role swap selected in the sidepanel seems to not be applied anymore (at least visually, have not tried inside ToB yet). It'd be nice if there was a config option to save the value to a hidden config value (using ``ConfigManager``) which then can be loaded in ``StartUp``.

**Comment by EIKOOT** [comment]
Yes, currently user has to set it every time he restarts his client. I usually use different swaps depending on the scale/role which change constantly, so thought default setting might be unnecessary. Could add it tho
