### ISSUE TITLE
Change sidepanel logo

### ISSUE THREAD

**Issue by YvesW** [EIKOOT/nyloer#6]
You are using the Nespresso logo as the sidepanel logo. RuneLite cannot distribute copyrighted material. Please change it.

**Comment by EIKOOT** [comment]
Yes, was not aware of it, Will change it soon

**Comment by EIKOOT** [comment]
https://github.com/EIKOOT/nyloer/commit/57a4f6dc43b7675256fac6fd2f13c303bc48f22d
